# What is Numpy?

Numpy is a Python library for scientific computing. 

In [5]:
import numpy as np

In [6]:
#create an array of 10 zeros

x = np.zeros(10)

In [7]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#shape of x

np.shape(x)

(10,)

In [9]:
# type of x

type(x)

numpy.ndarray

In [10]:
# data type

type(x[0])

numpy.float64

## Let's define 2 random arrays 1D and 2D

In [11]:
import random

x = np.random.randint(10, size = 6) # this command creates an array of non-negative numbers of size 6 with entries less than 10 
y = np.random.randint(10, size= (4,4))

In [12]:
x

array([9, 2, 5, 0, 7, 8])

In [13]:
y

array([[5, 6, 0, 8],
       [7, 1, 5, 6],
       [7, 4, 8, 0],
       [4, 8, 1, 3]])

In [14]:
x.shape

(6,)

In [15]:
y.shape #shape of y

(4, 4)

In [16]:
y.size # size of y

16

In [17]:
type(y)

numpy.ndarray

In [18]:
y.ndim # dimension of y

2

In [19]:
x+y # an error occurs here because we cannot add two arrays of different sizes

ValueError: operands could not be broadcast together with shapes (6,) (4,4) 

In [ ]:
x[2]

In [20]:
y[1:, 1:] 

array([[1, 5, 6],
       [4, 8, 0],
       [8, 1, 3]])

## Reshaping an array

In [21]:
x.reshape( (2,3))

array([[9, 2, 5],
       [0, 7, 8]])

In [22]:
x

array([9, 2, 5, 0, 7, 8])

# Exploring Numpy's functions

In [23]:
x = np.arange(10)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
x - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [27]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
x + x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
x - x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [31]:
x**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [32]:
x**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [33]:
x/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## Logical Operators

In [34]:
x = 1
y = 2

In [35]:
x > y

False

In [36]:
x ==2

False

In [37]:
x <y 

True

## Sin/Cos functions

In [38]:
x = np.arange(5)

In [39]:
x

array([0, 1, 2, 3, 4])

In [40]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [41]:
np.tan(x)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [42]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [43]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [44]:
np.log(x) # What goes wrong here?

<ipython-input-44-3f0bee98ad49>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x) # What goes wrong here?


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

## Max & Min

In [45]:
x = np.random.random(10) # it creates an array of random numbers between 0 and 1

In [46]:
x

array([0.27821079, 0.14086254, 0.05296349, 0.02493947, 0.27512139,
       0.14749329, 0.50721927, 0.65626949, 0.41191624, 0.41465598])

In [47]:
np.sum(x)

2.909651948923714

In [48]:
np.max(x)

0.6562694870933969

In [49]:
np.min(x)

0.024939467930523485

In [50]:
np.mean(x)

0.2909651948923714

In [51]:
np.std(x)

0.1952139364667085

In [52]:
np.sqrt(np.var(x))

0.1952139364667085

In [53]:
np.var(x)

0.03810848099082811

In [54]:
np.prod(x)

1.1942760029322185e-07